# -*- coding: utf-8 -*-
"""Atividade_RAG_Avançado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cJ3Fw6JuLPv1HCDY_f2vDWzYsOfC1Yz
"""

!pip install -q chromadb sentence-transformers maritalk requests

import os
from google.colab import userdata

MARITACA_API_KEY = userdata.get('MARITACA_API_KEY')
print('✅ API key carregada com sucesso!')

corpus_raw = [
    {
        "artigo": "Art. 1º",
        "capitulo": "Capítulo I — Definições e Fundamentos",
        "texto": "A presente Resolução estabelece normas para o desenvolvimento, a governança, a auditoria, o monitoramento e o uso responsável de soluções que adotam técnicas de inteligência artificial (IA) no âmbito do Poder Judiciário, com o objetivo de promover a inovação tecnológica e a eficiência dos serviços judiciários de modo seguro, transparente, isonômico e ético, em benefício dos jurisdicionados e com estrita observância de seus direitos fundamentais."
    },
    {
        "artigo": "Art. 2º",
        "capitulo": "Capítulo I — Definições e Fundamentos",
        "texto": "O desenvolvimento, a governança, a auditoria, o monitoramento e o uso responsável de soluções de IA pelo Poder Judiciário têm como fundamentos: o respeito aos direitos fundamentais e aos valores democráticos; a promoção do bem-estar dos jurisdicionados; a centralidade da pessoa humana; a participação e a supervisão humana em todas as etapas dos ciclos de desenvolvimento; a promoção da igualdade, da pluralidade e da justiça decisória; e a proteção de dados pessoais, o acesso à informação e o respeito ao segredo de justiça."
    },
    {
        "artigo": "Art. 3º",
        "capitulo": "Capítulo I — Definições e Fundamentos",
        "texto": "O desenvolvimento, a governança, a auditoria, o monitoramento e o uso responsável de soluções de IA pelos tribunais têm como princípios: a justiça, a equidade, a inclusão e a não-discriminação abusiva ou ilícita; a transparência, a eficiência, a explicabilidade, a contestabilidade, a auditabilidade e a confiabilidade das soluções que adotam técnicas de inteligência artificial; a segurança jurídica e a segurança da informação; e a supervisão humana efetiva, periódica e adequada no ciclo de vida da inteligência artificial."
    },
    {
        "artigo": "Art. 4º — Definições",
        "capitulo": "Capítulo I — Definições e Fundamentos",
        "texto": "Para o disposto nesta Resolução, consideram-se: sistema de inteligência artificial (IA): sistema baseado em máquina que processa dados e gera resultados de decisão, recomendação ou conteúdo; inteligência artificial generativa (IAGen): sistema de IA destinado a gerar texto, imagens, áudio, vídeo ou código; viés discriminatório ilegal ou abusivo: resultado indevidamente discriminatório que cria, reproduz ou reforça preconceitos; explicabilidade: compreensão clara de como as decisões são tomadas pela IA; contestabilidade: possibilidade de questionamento e revisão dos resultados gerados pela IA."
    },
    {
        "artigo": "Art. 5º",
        "capitulo": "Capítulo II — Direitos Fundamentais",
        "texto": "No desenvolvimento, na implantação e no uso de soluções de inteligência artificial no Judiciário, os tribunais observarão a compatibilidade dessas soluções com os direitos fundamentais, especialmente aqueles previstos na Constituição da República ou em tratados de que a República Federativa do Brasil seja parte. A verificação de compatibilidade deverá ocorrer em todas as fases do ciclo de vida da solução de IA."
    },
    {
        "artigo": "Art. 7º",
        "capitulo": "Capítulo II — Direitos Fundamentais",
        "texto": "Os dados utilizados no desenvolvimento ou treinamento de modelos de inteligência artificial devem ser representativos de casos judiciais e observar as cautelas necessárias quanto ao segredo de justiça e à proteção de dados pessoais, nos termos da Lei nº 13.709/2018 (LGPD). Os dados deverão ser anonimizados sempre que possível."
    },
    {
        "artigo": "Art. 8º",
        "capitulo": "Capítulo II — Direitos Fundamentais",
        "texto": "Os produtos gerados pela inteligência artificial para suporte às decisões judiciais deverão preservar a igualdade, a não discriminação abusiva ou ilícita e a pluralidade. Deverão ser implementadas medidas preventivas para evitar o surgimento de vieses discriminatórios. Verificado viés discriminatório, deverão ser adotadas as medidas corretivas necessárias, incluindo a suspensão temporária ou a eliminação definitiva da solução."
    },
    {
        "artigo": "Art. 10º",
        "capitulo": "Capítulo III — Categorização dos Riscos",
        "texto": "São vedados ao Poder Judiciário o desenvolvimento e a utilização de soluções: que não possibilitem a revisão humana dos resultados; que valorem traços da personalidade para prever o cometimento de crimes; que classifiquem ou ranqueiem pessoas naturais com base em comportamento social para avaliação de direitos ou méritos judiciais; e a identificação de padrões biométricos para o reconhecimento de emoções."
    },
    {
        "artigo": "Art. 11º",
        "capitulo": "Capítulo III — Categorização dos Riscos",
        "texto": "Consideram-se de alto ou baixo risco as soluções que utilizem técnicas de inteligência artificial, conforme o Anexo de Classificação de Riscos. As soluções de alto risco deverão ser submetidas a processos regulares de auditoria e monitoramento contínuo. A categorização de alto risco será revista ao menos anualmente pelo Comitê Nacional de Inteligência Artificial do Judiciário."
    },
    {
        "artigo": "Art. 12º",
        "capitulo": "Capítulo IV — Medidas de Governança",
        "texto": "O tribunal desenvolvedor ou contratante deverá estabelecer processos internos para garantir a segurança dos sistemas de inteligência artificial, incluindo: medidas de transparência quanto ao emprego e à governança dos sistemas de IA; a prevenção e mitigação de potenciais vieses discriminatórios por meio de monitoramento contínuo; implementação de mecanismos de governança com definição de comitês internos responsáveis pela fiscalização; e desenvolvimento de soluções interoperáveis que possam ser compartilhadas entre diferentes órgãos judiciais."
    }
]

print(f'✅ Corpus carregado: {len(corpus_raw)} artigos')

def chunk_text(texto, chunk_size=60, overlap=15):
    """Divide um texto em chunks com sobreposição."""
    palavras = texto.split()
    chunks = []
    inicio = 0
    while inicio < len(palavras):
        fim = inicio + chunk_size
        chunk = ' '.join(palavras[inicio:fim])
        chunks.append(chunk)
        inicio += chunk_size - overlap
    return chunks

# Gerar chunks com metadados
chunks_com_metadados = []
for item in corpus_raw:
    sub_chunks = chunk_text(item['texto'])
    for i, chunk in enumerate(sub_chunks):
        chunks_com_metadados.append({
            'id': f"{item['artigo'].replace(' ', '_').replace('º', '')}_{i}",
            'texto': chunk,
            'artigo': item['artigo'],
            'capitulo': item['capitulo']
        })

print(f'✅ Total de chunks gerados: {len(chunks_com_metadados)}')
print(f'\n📌 Exemplo de chunk com metadados:')
print(f"  ID      : {chunks_com_metadados[0]['id']}")
print(f"  Artigo  : {chunks_com_metadados[0]['artigo']}")
print(f"  Capítulo: {chunks_com_metadados[0]['capitulo']}")
print(f"  Texto   : {chunks_com_metadados[0]['texto']}")

import chromadb
from sentence_transformers import SentenceTransformer

# Modelo multilíngue — funciona bem com português
print('🔄 Carregando modelo de embeddings...')
modelo_embedding = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
print('✅ Modelo carregado!')

# Inicializar ChromaDB em memória
client = chromadb.Client()

# Criar coleção
try:
    client.delete_collection('cnj_615_2025')
except:
    pass

colecao = client.create_collection('cnj_615_2025')

# Gerar embeddings e indexar
textos = [c['texto'] for c in chunks_com_metadados]
ids = [c['id'] for c in chunks_com_metadados]
metadados = [{'artigo': c['artigo'], 'capitulo': c['capitulo']} for c in chunks_com_metadados]

print('🔄 Gerando embeddings e indexando no ChromaDB...')
embeddings = modelo_embedding.encode(textos).tolist()

colecao.add(
    documents=textos,
    embeddings=embeddings,
    ids=ids,
    metadatas=metadados
)

print(f'✅ {len(textos)} chunks indexados com sucesso!')

def recuperar_chunks(pergunta, top_k=6):
    """Recupera os top-k chunks mais relevantes para a pergunta."""
    embedding_pergunta = modelo_embedding.encode([pergunta]).tolist()
    resultados = colecao.query(
        query_embeddings=embedding_pergunta,
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )
    chunks_recuperados = []
    for i in range(len(resultados['documents'][0])):
        chunks_recuperados.append({
            'texto': resultados['documents'][0][i],
            'artigo': resultados['metadatas'][0][i]['artigo'],
            'capitulo': resultados['metadatas'][0][i]['capitulo'],
            'distancia': resultados['distances'][0][i]
        })
    return chunks_recuperados

# Teste de recuperação
pergunta_teste = 'Quais são as vedações ao uso de IA no judiciário?'
chunks_recuperados = recuperar_chunks(pergunta_teste, top_k=6)

print(f'🔍 Pergunta: {pergunta_teste}')
print(f'\n📦 Top-{len(chunks_recuperados)} chunks recuperados (antes do reranking):\n')
for i, c in enumerate(chunks_recuperados):
    print(f'  [{i+1}] Distância: {c["distancia"]:.4f} | {c["artigo"]}')
    print(f'       {c["texto"][:100]}...')
    print()

import numpy as np

def similaridade_cosseno(vec1, vec2):
    """Calcula a similaridade de cosseno entre dois vetores."""
    vec1, vec2 = np.array(vec1), np.array(vec2)
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

def reranquear(pergunta, chunks, top_n=3):
    """Reordena os chunks por similaridade de cosseno e retorna os top-n."""
    embedding_pergunta = modelo_embedding.encode([pergunta])[0]

    for chunk in chunks:
        embedding_chunk = modelo_embedding.encode([chunk['texto']])[0]
        chunk['score_reranking'] = similaridade_cosseno(embedding_pergunta, embedding_chunk)

    chunks_reranqueados = sorted(chunks, key=lambda x: x['score_reranking'], reverse=True)
    return chunks_reranqueados[:top_n]

# Aplicar reranking
chunks_finais = reranquear(pergunta_teste, chunks_recuperados, top_n=3)

print(f'✅ Top-{len(chunks_finais)} chunks após re-ranqueamento:\n')
for i, c in enumerate(chunks_finais):
    print(f'  [{i+1}] Score: {c["score_reranking"]:.4f} | {c["artigo"]}')
    print(f'       {c["texto"][:120]}...')
    print()

import requests

def gerar_resposta_maritaca(pergunta, chunks_contexto):
    """Gera resposta usando a API da Maritaca com os chunks reranqueados como contexto."""

    contexto = '\n\n'.join([
        f"[{c['artigo']} — {c['capitulo']}]\n{c['texto']}"
        for c in chunks_contexto
    ])

    prompt = f"""Você é um assistente jurídico especializado na Resolução CNJ nº 615/2025,
que estabelece diretrizes para uso de Inteligência Artificial no Poder Judiciário brasileiro.

Use APENAS o contexto abaixo para responder. Se a resposta não estiver no contexto, diga que
não encontrou a informação.

CONTEXTO:
{contexto}

PERGUNTA: {pergunta}

RESPOSTA:"""

    headers = {
        'Authorization': f'Key {MARITACA_API_KEY}',
        'Content-Type': 'application/json'
    }

    payload = {
        'model': 'sabia-3',
        'messages': [{'role': 'user', 'content': prompt}],
        'max_tokens': 500,
        'temperature': 0.3
    }

    response = requests.post(
        'https://chat.maritaca.ai/api/chat/completions',
        headers=headers,
        json=payload
    )

    if response.status_code == 200:
        return response.json()['choices'][0]['message']['content']
    else:
        return f'Erro na API: {response.status_code} — {response.text}'

# Gerar resposta
print(f'❓ Pergunta: {pergunta_teste}\n')
resposta = gerar_resposta_maritaca(pergunta_teste, chunks_finais)
print(f'💬 Resposta do sabia-3:\n')
print(resposta)

def rag_avancado(pergunta, top_k=10, top_n=3):
    """
    Pipeline RAG Avançado completo:
    1. Recuperação Top-K no ChromaDB
    2. Re-ranqueamento por similaridade de cosseno
    3. Geração com Maritaca sabia-3
    """
    print(f'❓ Pergunta: {pergunta}')
    print('─' * 60)

    # Etapa 1: Recuperação
    chunks_recuperados = recuperar_chunks(pergunta, top_k=top_k)
    print(f'📦 {len(chunks_recuperados)} chunks recuperados (Top-{top_k})')

    # Etapa 2: Re-ranqueamento
    chunks_finais = reranquear(pergunta, chunks_recuperados, top_n=top_n)
    print(f'🔄 Re-ranqueamento aplicado → Top-{top_n} selecionados')
    print('\n📌 Chunks usados como contexto:')
    for i, c in enumerate(chunks_finais):
        print(f'  [{i+1}] Score: {c["score_reranking"]:.4f} | {c["artigo"]}')

    # Etapa 3: Geração
    print('\n💬 Resposta gerada pelo sabia-3:')
    print('─' * 60)
    resposta = gerar_resposta_maritaca(pergunta, chunks_finais)
    print(resposta)
    print('─' * 60)
    return resposta

# Testando com a mesma pergunta
rag_avancado('Quais são as vedações ao uso de IA no judiciário?')

perguntas = [
    'Quais são as vedações ao uso de IA no judiciário?',
    'O que é proibido no desenvolvimento de IA nos tribunais?',
    'Quais são os fundamentos do uso de IA no Poder Judiciário?',
    'O que é explicabilidade segundo a Resolução CNJ 615/2025?',
    'Como os tribunais devem tratar dados usados no treinamento de IA?'
]

for p in perguntas:
    rag_avancado(p)
    print('\n')

pergunta_comparativo = 'Como os tribunais devem tratar dados usados no treinamento de IA?'

# Antes: recuperação pura
chunks_sem = recuperar_chunks(pergunta_comparativo, top_k=6)

# Depois: reranking
chunks_com = reranquear(pergunta_comparativo, chunks_sem.copy(), top_n=3)

print('=' * 70)
print('📊 COMPARATIVO: Antes vs. Depois do Re-ranqueamento')
print('=' * 70)

print('\n🔴 ANTES — Top-6 por distância vetorial (ChromaDB):')
for i, c in enumerate(chunks_sem):
    print(f'  [{i+1}] Distância: {c["distancia"]:.4f} | {c["artigo"]}')

print('\n🟢 DEPOIS — Top-3 após re-ranqueamento por cosseno:')
for i, c in enumerate(chunks_com):
    print(f'  [{i+1}] Score: {c["score_reranking"]:.4f} | {c["artigo"]}')

print('\n✅ O re-ranqueamento reorganiza e filtra os chunks mais relevantes!')